Randomisation for loo_pit of discrete data.
stan-dev/rstantools pull request #121
Opened 2024-02-06 10:50 UTC by TeemuSailynoja

Fixes issue #22 

I added randomisation to the loo_pit function so that it can be used for discrete data too.

Essentially, when computing pit, we check if the posterior sample contains an exact match to the observation.
In the case an exact match is found, the pit is randomised.

I also added a check that the log weights are finite and not NULL, as well as a warning, if the loo_pit values contain values greater than 1, which can happen with non-normalized weights.

2024-02-07 18:21 UTC, jgabry requested changes
Thanks @TeemuSailynoja! Just a few minor comments.

2024-02-07 18:21 UTC, jgabry commented on tests/testthat/test-default-methods.R
> +  STATS = matrixStats::colLogSumExps(lw),
We don't have a dependency on matrixStats in rstantools. Can you change this to just do the column log sum exps using base R?

2024-02-07 18:21 UTC, jgabry commented on R/loo-functions.R
> +      pit <- stats::runif(1, pit, pit_sup)
Can you mention somewhere in the doc that randomization is used now so the results won't be reproduce without using the same seed?

2024-02-07 18:22 UTC, jgabry commented on tests/testthat/test-default-methods.R
> +  STATS = matrixStats::colLogSumExps(lw),
I think this should fix the R cmd check issue

2024-02-07 18:26 UTC, jgabry commented
Also, can you save the new RDS files using `saveRDS(..., version = 2)`? That should get rid of the message in R cmd check about serialization and adding a dependency on R > 3.5 (https://github.com/stan-dev/rstantools/actions/runs/7798510507/job/21295468864?pr=121#step:6:51). Although maybe we should require R > 3.5 anyway, but we can do that later.

2024-02-15 12:22 UTC, TeemuSailynoja commented
Thank you, @jgabry. I hope to have addressed all the requested changes and additions in the last commits.
Also, I fixed an error preventing some of the documentation being parsed, as there was a line break at the `>` in `GPL >= 3`, which caused the line starting with `>` to be parsed as a block quote.

2024-02-22 16:36 UTC, jgabry approved these changes
Thanks @TeemuSailynoja, this looks good!

2024-02-22 16:37 UTC, jgabry commented
@andrjohns The StanFunctions Support checks are failing due to a compilation issue with the lgpr package, but that must be unrelated to this PR (this PR doesn't touch anything relevant for that), so I will go ahead and merge and we can sort out whatever is causing those failures before we do a release.

2024-02-22 16:37 UTC, merged